import { compile, form } from "../core/request";
import {
  bodyText,
  escapeCSharp,
  escapeFSharp,
  escapeGo,
  escapeJava,
  escapeJs,
  escapeObjC,
  escapeOCaml,
  escapePhp,
  escapePowerShell,
  escapePy,
  escapeR,
  escapeRuby,
  escapeRust,
  escapeSh,
  escapeSwift,
  hasFormBody,
  hasJsonBody,
  hasMultipartBody,
  indent,
  operationName,
  stringifyLiteral,
  toHeaderObject,
  toKeyValueBody,
  isFileValue,
  DEFAULT_FILE_PATH,
  DEFAULT_FILE_NAME,
  DEFAULT_BINARY_MEDIA_TYPE,
  normalizeMethod,
  mediaTypeOf,
  kotlinValue,
  isContentTypeHeader,
  isContentLengthHeader,
  isTransferEncodingHeader,
  supportsRequestBody,
  requiresRequestBody,
  fileComment,
  formFieldValue,
  isBrowserForbiddenHeader,
  browserHeaders,
  nonBlankString
} from "../core/helpers";
import type { RequestIR } from "../types";

export {
  compile,
  form,
  bodyText,
  hasFormBody,
  hasJsonBody,
  hasMultipartBody,
  indent,
  operationName,
  stringifyLiteral,
  toHeaderObject,
  toKeyValueBody,
  isFileValue,
  escapeCSharp,
  escapeFSharp,
  escapeGo,
  escapeJava,
  escapeJs,
  escapeObjC,
  escapeOCaml,
  escapePhp,
  escapePowerShell,
  escapePy,
  escapeR,
  escapeRuby,
  escapeRust,
  escapeSh,
  escapeSwift,
  DEFAULT_FILE_PATH,
  DEFAULT_FILE_NAME,
  DEFAULT_BINARY_MEDIA_TYPE,
  normalizeMethod,
  mediaTypeOf,
  kotlinValue,
  isContentTypeHeader,
  isContentLengthHeader,
  isTransferEncodingHeader,
  supportsRequestBody,
  requiresRequestBody,
  fileComment,
  formFieldValue,
  isBrowserForbiddenHeader,
  browserHeaders,
  nonBlankString
};

export function multipartLines(
  request: RequestIR,
  pairRenderer: (name: string, value: any, file: boolean) => string,
): string[] {
  return toKeyValueBody(request.body?.value).map((entry) =>
    pairRenderer(entry.name, entry.value, entry.file),
  );
}
